
name: tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - master
      - develop
jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '14.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.19.x'
          channel: 'beta'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test